---
title: "Dynamic Scheduling Preregistration"
author: "Daniel R. Little"
date: "19/04/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Study Information

### 1.	Title 

<!-- 
Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement.
Example: Effect of sugar on brownie tastiness. 
More info: The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.
-->

Human scheduling of dynamic perceptual tasks 

### 2.	Authorship

<!--
List authors and affiliations as applicable. Placing a number or letter in upward arrows, (e.g. ^2^) creates a superscript
--> 

Daniel R. Little^1^ 
Ruby Sternberg^1^ 
Ami Eidels^2^
Deborah J. Lin^1^


^1^ The University of Melbourne
^2^ The University of Newcastle

### 3. Description

<!--
Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. 
Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. 
More info: The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration. 
-->

Scheduling theory is concerned with the development of policies which determine the “optimal allocation of resources, over time, to a set of tasks” (Parker, 1995). Scheduling problems have been studied extensively in the context of operations research and computer science, where optimal policies have been established for many cases. However, almost no research has examined how cognitive and perceptual mechanisms perform with respect to these optimal policies. 

We know that switching between tasks leads to context shift costs (Monsell, 2003) and that multitasking leads to inefficiencies and errors (Strayer & Johnston, 2001). But it is unclear whether people are sensitive to the efficiency of different schedules and whether these costs impact on the optimality of human scheduling. The current project will develop a new framework for studying the scheduling of mental processes in human cognition.

For many types of goals, such as minimizing the number of tasks completed after a deadline or completing as many tasks as possible in a given length of time, an optimal schedule can be determined (Chretienne et al., 1995). In the present study, we are focused on the scheduling of tasks that vary in difficulty where the goal is to complete as many tasks as possible prior to the deadline. In this case, it is optimal to complete subtasks in order of shortest to longest completion time.

Future experiments will additionally vary the utility/reward of each subtask, the overall goal, and whether or not the difficulty needs to be learned or is described. 

In this study, each subtask is a Random Dot Kinematogram (RDK). In an RDK, dots are moving across an aperture on the screen in a pseudo-random fashion. The participant must to determine whether more dots are moving coherently to the right or to the left. Multiple RDK patches will be presented on the selection screen. Participants will click on the RDK they want to complete, indicate the direction of motion in that patch, and then return to the main screen to select the next RDK. The RDK's will vary in coherence and consequently, difficulty, and average completion time (Ludwig & Evens, 2017). 

RDK difficulty will be constant across trials. RDK difficulty is indicated by the coherence of the dots as they move on the selection screen. RDKs will be presented in onscreen at the four compass points (North, South, East, West). Location of each difficulty level will be either fixed across trials or random across trials. Once the RDK is selected, the coherence will remain the same but the direction of motion will be resampled randomly (e.g., left or right).

In these experiments, the RDK's will be moving on the selection screen so that perceptual difficutly information can be ascertained prior to selecting which RDK to complete. In Experiment 1, once the RDK is selected all of the RDKs, except for the selected RDK will stop until the direction decision is made. In Experiment 2, once the RDK is selected, all of the RDKs will continue moving but the selected RDK will be highlighted (e.g., by a red rectangle) until the direction decision is made. 

### 4.	Hypotheses

<!-- 
List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis. 
Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. 
-->

The optimal policy to minimize the number of tasks completed after the deadline (or i.e., to maximize the number of tasks completed before the deadline) is to complete shortest subtask first. We will determine whether participants converge to this optimal schedule. We will compare scheduling both with and without a deadline and expect greater optimality when participants have to complete the RDK task under a deadline. We additionally expect greater optimality when difficulty location is held constant compared to when it is varied from trial to trial. 

## Design Plan

<!-- 
In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. 
-->

In this experiment, participants will complete multiple trials for selecting and completing random dot kinematogram (RDK) tasks. On each trial, participants will be shown a set of four RDKs labelled Easy, Medium, Hard, and Very Hard. The labels correspond to the difficulty of the RDK instantiated by the proportion of dots moving in a coherent direction. Participants will select and complete one RDK at a time, in any order, completing as many as possible before a deadline. 

Before completing the deadline task, participants will complete 10 trials with no deadline. This will help participants learn the task, explore strategies, and allow us to compare the optimality of responding between a no deadline and a deadline condition.

### 5.	Study Type 

<!-- 
Delete all that do not apply.
-->

- Experiment - A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.

<!--
- Observational Study - Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, ñnatural experiments,î and regression discontinuity designs.

- Meta-Analysis - A systematic review of published studies.

- Other (explain your study type)
-->

### 6.	Blinding

<!-- 
Blinding describes who is aware of the experimental manipulations within a study. Delete all that do not apply. 
-->

<!--
- No blinding is involved in this study.
-->

- For studies that involve human subjects, they will not know the treatment group to which they have been assigned. However, the coherence location condition - fixed or random - will be obvious after the second trial. 

<!--
- Personnel who interact directly with the study subjects (either human or non-human subjects) will not be aware of the assigned treatments. (Commonly known as “double blind”).

- Personnel who analyze the data collected from the study are not aware of the treatment applied to any given group.
-->


### 7.	Is there any additional blinding in this study?

<!-- 
Describe any additional blinding procedures that were not covered by the options above. 
-->

N/A

### 8.	Study design

<!-- 
Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.
Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. 
More info: This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information. 
-->

Difficulty location will be randomized across subjects. Four coherence levels will be used to manipulate difficulty (proportions of 0.8, 0.5, 0.1, and 0.0). A single deadline of e.g., 6 seconds will be tested and compared to a no deadline condition (i.e., a long trial length of 30 seconds).

### 9.	Randomization

<!-- 
If you are doing a randomized study, how will you randomize, and at what level?
Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at http://random.org. 
More info: Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.
-->

Location of RDKs (i.e., RDK difficulty) will be randomized across participants. RDK direction and instantiation is randomized from selection to selection. RDK coherence is held constant across trials.

## Sampling Plan 

<!-- 
In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. 
-->

### 10. Existing data

<!-- 
Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact the COS if you have questions about how to answer this question (prereg@cos.io). 
Delete all that do not apply. 
-->

<!--
- Registration prior to creation of data: As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized. 
-->


- Registration prior to any human observation of the data: As of the date of submission, the data exist but have not yet been quantified, constructed, observed, or reported by anyone - including individuals that are not associated with the proposed study. Examples include museum specimens that have not been measured and data that have been collected by non-human collectors and are inaccessible.
<!--
- Registration prior to accessing the data: As of the date of submission, the data exist, but have not been accessed by you or your collaborators. Commonly, this includes data that has been collected by another researcher or institution.

- Registration prior to analysis of the data: As of the date of submission, the data exist and you have accessed it, though no analysis has been conducted related to the research plan (including calculation of summary statistics). A common situation for this scenario when a large dataset exists that is used for many different studies over time, or when a data set is randomly split into a sample for exploratory analyses, and the other section of data is reserved for later confirmatory data analysis.

- Registration following analysis of the data: As of the date of submission, you have accessed and analyzed some of the data relevant to the research plan. This includes preliminary analysis of variables, calculation of descriptive statistics, and observation of data distributions. Please see cos.io/prereg for more information. 
-->


### 11.	Explanation of existing data

<!-- 
If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study. 
Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. 
More info: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. 
-->

Only CI Little has access to the data, which is stored in a password secured database. CI Little has inspected the raw data to ensure that it has been recorded properly. No summary analysis of the data has been undertaken. 

### 12.	Data collection procedures

<!-- 
Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use. 
Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries.
More information: The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear. 
--> 

Prticipants will be recruited from the University of Melbourne's or the University of Newcastle's Research Experience Program. Participants will be reimbursed 1 credit for participation. 

### 13.	Sample size

<!-- 
Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis?
Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. 
More information: For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number. 
-->

We will recruit 50 participants in the fixed and random location conditions (N = 100 total). 

In each condition, participants will complete ten no deadline scheduling trials and thirty deadline scheduling trials via a web browser.


### 14. Sample size rationale 

<!-- 
This could include a power analysis or an arbitrary constraint such as time, money, or personnel.
Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. 
More information: This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to “fill in the blanks.” Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints. 
-->

This is a preliminary study. Sample size is chosen based on pragmatic considerations.

### 15. Stopping rule 

<!-- 
If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 
Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. 
More information: You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained. 
-->

Sampling will be stopped after 50 participants have been collected or as close as possible given asynchronicity between remote enrolment in the experiment and completion of the experiment. .

## Variables 

<!-- 
In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. 
-->



### 16. Manipulated variables

<!-- 
Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. 
Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. 
More information: For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.
-->

We will manipulate the coherence and direction of four RDK tasks and the deadline available for selection and completion of the four tasks on each trial. We will additionally manipulate whether there was a deadline or not.

### 17. Measured variables 

<!-- 
Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.
Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being ‘not at all’, 7 being ‘a great deal’) and ‘How good did the brownie taste’ (on a scale of 1-7, 1 being ‘very bad’, 7 being ‘very good’). 
More information: Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'
-->

The main variable is the order in which subtasks are completed. Secondary variables are the accuracy and completion time of the RDK subtasks. 

### 18. Indices 

<!-- 
If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.
Example: We will take the mean of the two questions above to create a single measure of ‘brownie enjoyment.’ 
More information: If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as “means” do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, “biodiversity index” is too broad, whereas “Shannon’s biodiversity index” is appropriate. 
-->

N/A

## Analysis Plan

<!-- 
You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.
A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. 
-->

### 19. Statistical models

<!-- 
What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article. 
Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. 
More information: This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples: 
If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.
-->

For each participant, the optimal order of each location will be determined (i.e., from easiest to hardest). The first analysis will compute something like Kendall's Tau, rank-order distance. What we want is the distance of the selected options from the optimal solutions, which is Kendall's Tau. However, because a participant may run out of time, there may be missing values. To handle these values, for each trial, we find the orders which partially match the selected order and compute: (1) the maximum distance of those possible orders and the optimal solution and (2) the average distance of those possible orders and the optimal solution. 

We will examine the distribution of distances across participants to determine how much they deviate from optimal. Bayesian analysis will be used to characterise the posterior uncertainty in distance across trials.

We will perform a similar analysis using the proportion of first-optimal responses (i.e., the proportion of responses in which the first chosen option is the easiest).

We will additionally create "spatial-order" strategies (e.g., clockwise strategy, anti-clockwise strategy) and compute the partial-matching Kendall's Tau measure of the response to these spatial orders. These strategies may be non-optimal, depending on the random distribution of difficulties; nonetheless, participants may adopt these strategies.

For completeness, we will additionally analyse the completion time and accuracy of the RDK task to ensure that coherence mapped to difficulty and average completion time the expected manner.

We will compare the optimality of the first 10 untimed trials against the first 10 deadline trials and the last 10 deadline trials using a Bayesian one-way ANOVA and a hierarchical Bayesian model described below.

### 20. Transformations 

<!-- 
If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process.
Example: The “Effect of sugar on brownie tastiness” does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), ‘sweet’ could be dummy coded with ‘not sweet’ as the reference category. 
More information: If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be. 
-->

N/A

### 21. Inference criteria 

<!-- 
What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?
Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. 
More information: P-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few “wrong” answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.
-->

Posterior parameter estimation will be used for inference. Optimality (measured using normalised Kendall's Tau adjusted for missing data as described above) will be given a uniform Beta(1,1) prior in each condition. We will compare two models, one in which the hyperpriors are free to vary across the untimed, deadline (first 10), and deadline (last 10) conditions, and one in which the hyperpriors are fixed. Posterior parameter estimation and DIC will be used to examine whether there is a credible difference in optimality between deadline conditions.

### 22. Data exclusion 

<!-- 
How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check?
Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. 
More information: Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.
-->

Initial analysis will not exclude any data. Followup analyses may exclude data on the basis of RDK completion time.

### 23. Missing data

<!-- 
How will you deal with incomplete or missing data?
Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis.
More information: Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis. 
--> 

Participants will be excluded if they do not complete all trials.

### 24. Exploratory analysis

<!-- 
If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time. 
Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences.
-->

Most of the data analyses considered so far may be considered exploratory in that we make no particular hypothesis as to whether scheduling should be optimal or not.

## Other 

### 25. Other 

<!-- 
If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. 
-->

N/A

## References 

* Chretienne, P., Coffman Jr, E. G., Lenstra, J. K., & Liu, Z. (1997). Scheduling theory and its applications. Journal of the Operational Research Society, 48(7), 764-765.

* Ludwig, C. J., & Evens, D. R. (2017). Information foraging for perceptual decisions. Journal of Experimental Psychology: Human Perception and Performance, 43(2), 245.

* Monsell, S. (2003). Task switching. Trends in cognitive sciences, 7(3), 134-140.

* Parker, R. G. (1996). Deterministic scheduling theory. CRC Press.

* Strayer, D. L., & Johnston, W. A. (2001). Driven to distraction: Dual-task studies of simulated driving and conversing on a cellular telephone. Psychological science, 12(6), 462-466.
